const DEPTH_CHART_SLOT_COUNTS = {
  QB: 3,
  HB: 4,
  FB: 3,
  WR: 6,
  TE: 3,
  LT: 3,
  LG: 3,
  C: 3,
  RG: 3,
  RT: 3,
  LEDG: 3,
  REDG: 3,
  DT: 5,
  SAM: 3,
  MIKE: 4,
  WILL: 3,
  CB: 5,
  FS: 3,
  SS: 3,
  K: 3,
  P: 3,
  KR: 5,
  PR: 5,
  KOS: 3,
  LS: 3,
  '3DRB': 3,
  PWHB: 3,
  SLWR: 3,
  RLE: 3,
  RRE: 3,
  RDT: 3,
  SUBLB: 3,
  SLCB: 3,
  NT: 3,
  GAD: 3,
};

const DEFAULT_DEPTH_CHART_SLOT_RULES = {
  QB: [{ position: 'QB' }],
  HB: [{ position: 'HB' }],
  FB: [{ position: 'FB' }],
  WR: [{ position: 'WR' }],
  TE: [{ position: 'TE' }],
  LT: [{ position: 'LT' }],
  LG: [{ position: 'LG' }],
  C: [{ position: 'C' }],
  RG: [{ position: 'RG' }],
  RT: [{ position: 'RT' }],
  LEDG: [{ position: 'LEDG' }],
  REDG: [{ position: 'REDG' }],
  DT: [{ position: 'DT' }],
  SAM: [{ position: 'SAM' }],
  MIKE: [{ position: 'MIKE' }],
  WILL: [{ position: 'WILL' }],
  CB: [{ position: 'CB' }],
  FS: [{ position: 'FS' }],
  SS: [{ position: 'SS' }],
  K: [{ position: 'K' }],
  P: [{ position: 'P' }],
  KR: [{ position: 'WR' }, { position: 'HB' }, { position: 'CB' }],
  PR: [{ position: 'WR' }, { position: 'HB' }, { position: 'CB' }],
  KOS: [{ position: 'K' }],
  LS: [{ position: 'C' }, { position: 'TE' }, { position: 'LG' }, { position: 'RG' }],
  '3DRB': [{ position: 'HB' }],
  PWHB: [{ position: 'HB' }, { position: 'FB' }],
  SLWR: [{ position: 'WR' }, { position: 'TE' }],
  RLE: [{ position: 'LEDG' }, { position: 'REDG' }, { position: 'SAM' }],
  RRE: [{ position: 'REDG' }, { position: 'LEDG' }, { position: 'WILL' }],
  RDT: [{ position: 'DT' }],
  SUBLB: [{ position: 'MIKE' }, { position: 'SAM' }, { position: 'WILL' }],
  SLCB: [{ position: 'CB' }, { position: 'FS' }, { position: 'SS' }],
  NT: [{ position: 'DT' }],
  GAD: [{ position: 'MIKE' }, { position: 'SAM' }, { position: 'WILL' }, { position: 'SS' }, { position: 'FS' }, { position: 'CB' }],
};

const DEPTH_CHART_SLOTS = Object.keys(DEPTH_CHART_SLOT_COUNTS);

module.exports = {
  DEPTH_CHART_SLOT_COUNTS,
  DEFAULT_DEPTH_CHART_SLOT_RULES,
  DEPTH_CHART_SLOTS,
};
